[package]
name = "gol"
version = "0.1.0"
authors = ["Vishal <vishal@local.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"